### ISSUE TITLE
.Rmd file fail to knit

### ISSUE THREAD

**Issue by iris-yi-jiang** [numbats/moodlequiz#1]
Hi Emi,

I tried to directly knit the `draw_scatterplots.Rmd` file,  it did not work and returned the following error message `Error: 'moodlequiz_cloze' is not an exported object from 'namespace:moodlequiz' Execution halted`.

And then, I tried this approach. It is executable, but the same error message is till returned.
```
ex_scatter <- "~/repos/moodlequiz/inst/examples/draw-scatterplots.Rmd"
rmarkdown::render(ex_scatter)
#> Error: 'moodlequiz_cloze' is not an exported object from 'namespace:moodlequiz'
```

**Comment by emitanaka** [comment]
This error looks like perhaps the package was not re-installed? Can you try 
```r
remotes::install_github("emitanaka/moodlequiz")
```
and try knitting again?

**Comment by iris-yi-jiang** [comment]
It worked! Thank you, Emi!

I was at the cloned package directory and called `devtools::load_all()`. I thought that would be enough. Could I please ask what makes `devtools::load_all()` insufficient in this case?

**Comment by emitanaka** [comment]
Great! `devtools::load_all()` simulates install and load of a package but when you knit, it's not using your current environment so it tries to use the actual installed version (which probably was the previous version or not yet installed).
