### ISSUE TITLE
New API with direct XML implementaiton

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#13]
A new API is proposed with `cloze <answer>` replaced with `r answer(<answer>)` along with direct translation to Moodle XML via pandoc.

Comparison with `exams` shown below.

![moodlequiz-and-exams-comparison](https://user-images.githubusercontent.com/7620319/220833828-3f12f54c-86d3-49a8-bfef-e5735801ed13.png)

**Comment by mitchelloharawild** [comment]
Implemented in `moodlequiz` format with answer types given in `answer.R`
