### ISSUE TITLE
Disable XML preview

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#14]
Or make the preview a HTML version

**Comment by emitanaka** [comment]
Current format opens xml file, which people have different defaults for (xcode, illustrator etc)

**Comment by mitchelloharawild** [comment]
I agree that the solution would be to create a HTML preview but this would be time consuming and low priority.

**Comment by mitchelloharawild** [comment]
In the short term we could output a dummy HTML file which shows instructions on how to import the questions into moodle.

**Comment by mitchelloharawild** [comment]
To disable previews, you can use `(No Preview)`.
![image](https://github.com/numbats/moodlequiz/assets/16127127/07bdd0fd-1c62-443d-bbf7-304467e1fb21)
