### ISSUE TITLE
`times` argument (multiple instances)

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#16]
New syntax doesn't have support for this -- moodle XML doesn't have this and it seems like it was more of a feature of `exams` package. 

Is this more natural to include as part of YAML argument OR a function that parses the Rmd file with `times` argument?

**Comment by emitanaka** [comment]
@iris-yi-jiang prefers to be on YAML

**Comment by emitanaka** [comment]
@thomas-fung think YAML is more natural

**Comment by emitanaka** [comment]
`exams2moodle()` with `n` argument for number of instances

**Comment by mitchelloharawild** [comment]
Additional information from #21

> ### Replicated questions for 'random questions'
>
> Add a `replications` argument to the front matter which controls how many times the body of the materials are replicated (for say sampling and randomisation of question inputs like data).
