### ISSUE TITLE
Different way to specify answers for single and multi-choice

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#19]
consider making a new engine for it, e.g. 

---
|- name: some question

What's my favorite color?

````
```{singlechoice, correct = 1}
- white
- black
- grey
- blue
```
````

**Comment by emitanaka** [comment]
````
```{singlechoice, feedback="Incorrect!"}
- white #<< weight=0.25, feedback="correct!"
- black
- grey
- blue
```

````

**Comment by mitchelloharawild** [comment]
A more generic answer passing tool for non-cloze questions is needed for #25, there are some overlap in these types which should be consistent.

A new engine would limit our ability to generate these single-question questions from data with randomisation. I also want to stay as close as possible to the moodle XML spec so we have less of a learning gap and we can inherit documentation from Moodle. Therefore I'm closing this in favour of #25.
