### ISSUE TITLE
Consider removing `---` question separator in favour of using headers

### ISSUE THREAD

**Issue by mitchelloharawild** [numbats/moodlequiz#29]
Having both causes some design conflicts for the package, where empty questions seem to be part of the design.

For example:

```markdown
---
<yaml_front_matter>
---

# Category

## Math
```

Would be treated as an empty question (started by the second `---`), followed by a category and a question.

**Comment by mitchelloharawild** [comment]
Removing this would remove the `|-` prefix for question type/attributes, which are now provided in header attributes (`## question {type = cloze}`). This seems more consistent with the quarto design language, but is a bit ugly when many attributes are specified.

Thoughts welcomed, cc @emitanaka

**Comment by emitanaka** [comment]
Sound good! We haven't disseminated the package widely so breaking changes shouldn't be an issue at this stage.
