### ISSUE TITLE
Randomise questions 

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#6]

**Comment by emitanaka** [comment]
@iris-yi-jiang says this is high priority! Shuffle feature is provided in `exams`.

**Comment by emitanaka** [comment]
`exshuffle` and only works for MC questions

**Comment by mitchelloharawild** [comment]
Shuffle functionality is available in single and multiple choice questions.
Randomisation of questions is better described in #21

**Comment by mitchelloharawild** [comment]
The other question type which supports shuffling is 'matching', described in #22
