### ISSUE TITLE
local tolerance factor

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#7]
Current tolerance only specified globally for the file

**Comment by mitchelloharawild** [comment]
Tolerance can now be specified for each numerical response question via `answer_numerical(tolerance = )`, and numerical response questions use the `<tolerance>` tag which is specified in the question header. For example:
```
---
|- name: Numerical
|- type: numerical
|- tolerance: 10
```

Providing answers for this type of question is not yet supported (#25)
