### ISSUE TITLE
Add `expoints`

### ISSUE THREAD

**Issue by emitanaka** [numbats/moodlequiz#9]
Give different points to each subquestions

**Comment by mitchelloharawild** [comment]
Related to #10

**Comment by mitchelloharawild** [comment]
Closing as this is now supported in the new `moodlequiz` format. The grade value for a section is specified with `defaultgrade` (strange name inherited from Moodle's XML format), we can alias this later.

```
---
|- type: essay
|- name: Write
|- defaultgrade: 6
```
